version: "3"
services:
  nginx:
    container_name: nginx1
    hostname: nginx1
    image: nginx
    ports:
      - "8081:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
      - ./sslt:/etc/ssl/sslt:rw
    restart: on-failure:5